### PR TITLE
Fixes parts (2) and (3) of issue #226

### PR DESCRIPTION
**Pull request by msuchard**

### CODE REVIEW

**Comment by matsen** [comment]
@msuchard I'll close this unless told otherwise. Thanks for trying!

**Comment by msuchard** [comment]
This `PR` is critical if you want `libsbn` to compile on macOS < 10.14 (i.e. with real GPUs).

**Comment by matsen** [comment]
OK, I think for that the flag

    env.Append(CXXFLAGS=["-D_LIBCPP_DISABLE_AVAILABILITY"])

is essential, but not the pyenv stuff. 

If that's correct, I'd prefer a PR with just that line because it doesn't look like we're going to try to support pyyenv. If you are just as happy for me to copy-paste the MacOS line into another branch I'm happy to do that too.

Just let me know!

**Comment by msuchard** [comment]
Please copy and paste that one line, then close.

**Comment by matsen** [comment]
Done in https://github.com/phylovi/libsbn/commit/25665e255ffdfec6c15fa2bc6eeb82ebea5264be

**Pull request closed without merging**
